spring.application.name=tks-store
#server.servlet.context-path=/app
server.port=8080
#server.address=192.168.2.2
spring.main.allow-bean-definition-overriding=true
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tks
spring.datasource.username=postgres
#spring.datasource.password=admin
spring.datasource.password=309927605
spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=false
server.http.keep-alive=false

server.tomcat.max-swallow-size=-1
server.tomcat.max-http-header-size=64KB
server.tomcat.connection-timeout=60s
spring.mvc.async.request-timeout=60000
